name: Deploy

on:
  workflow_dispatch: # Trigger manually

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'App/App.Server'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup DotNet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Build DotNet
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_121155F2AC32461ABD708E07BBA86972 }} # See also https://github.com/steinertech/Analyze/settings/secrets/actions
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F2AC48361B5E47B7BBA3C6A41BD35F78 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6746E4C4C80D4DAB8F5971E6C45F7D4B }}

      - name: Deploy Azure Function
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'stc001appFunction'
          slot-name: 'Production'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'

      - name: Checkout Pages
        uses: actions/checkout@v4
        with:
          repository: steinertech/GitHubPages
          path: pages
          token: ${{ secrets.PAGES_PAT }} # See also https://github.com/settings/personal-access-tokens and renew GitHub Pages PAT. Enter PAGES_PAT at https://github.com/steinertech/Analyze/settings/secrets/actions Repository secrets.

      - name: Set Git user
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com" # See also https://github.com/settings/emails
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
      
      - name: Deploy.sh Make Executable
        run: chmod +x .github/workflows/deploy.sh
      
      - name: Deploy.sh Run
        run: .github/workflows/deploy.sh    

