name: Deploy

on:
  workflow_dispatch: # Trigger manually

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'App/App.Server'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup DotNet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Build DotNet
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd
      
      - name: Login to Azure # Azure portal Function App Deployment Center connect to GitHub. This will set GitHub secret AZUREAPPSERVICE_CLIENTID. Create Identity stc001appFunctionDeploy. Go to Azure function Access control (IAM) and add Website Contributor role.
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A1C3E8AD79864649A67189E5EC3565A1 }} # See also https://github.com/steinertech/Analyze/settings/secrets/actions 
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3E4E22D09B6E467FB47CDE228E825335 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E4978D749A3943DF8BAA9CB9D1898C83 }}

      - name: Deploy Azure Function # Open https://stc001appfunction.azurewebsites.net/api/data 
        uses: Azure/functions-action@v1 # Add custom domain api.example.com
        id: fa
        with:
          app-name: 'stc001appFunction2'
          slot-name: 'Production'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'

      - name: Checkout Pages
        uses: actions/checkout@v4
        with:
          repository: steinertech/GitHubPages
          path: pages
          token: ${{ secrets.PAGES_PAT }} # See also https://github.com/settings/personal-access-tokens and renew GitHubPages PAT or create new with Permission "Contents" read and write. Enter PAGES_PAT at https://github.com/steinertech/Analyze/settings/secrets/actions Repository secrets.

      - name: Set Git user
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com" # See also https://github.com/settings/emails
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
      
      - name: Deploy.sh Make Executable
        run: chmod +x .github/workflows/deploy.sh
      
      - name: Deploy.sh Run
        run: .github/workflows/deploy.sh    


